name: pdf_viewer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_pdfviewer: ^28.2.6
  get: ^4.7.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  http: ^1.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  geolocator: ^10.1.0
  permission_handler: ^11.4.0
  package_info_plus: ^8.3.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
